"""Generation de fichiers d'exemple pour les tests (G-code et 3MF)."""
from __future__ import annotations

import base64
import io
import json
import zipfile
from pathlib import Path

#: PNG 2x2 valide, sert de miniature de test.
TINY_PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAF0lEQVQI12P8z8Dwn4GBgYGJAQ"
    "0MTgYGAA0jAQGkqYU2AAAAAElFTkSuQmCC"
)


def make_gcode(
    *,
    material: str = "PLA",
    color: str = "#FF0000",
    print_time: str = "1h 12m 30s",
    layers: int = 240,
    nozzle: float = 0.4,
    with_thumbnail: bool = True,
    body_lines: int = 40,
) -> str:
    """G-code au format Creality Print / Orca (metadonnees en tete et en pied)."""
    encoded = base64.b64encode(TINY_PNG).decode()
    thumbnail = ""
    if with_thumbnail:
        thumbnail = "\n".join(
            [f"; thumbnail begin 32x32 {len(encoded)}"]
            + [f"; {encoded[i:i + 60]}" for i in range(0, len(encoded), 60)]
            + ["; thumbnail end"]
        )

    head = f"""; generated by CrealityPrint 6.1.0 on 2026-05-02
{thumbnail}
; nozzle_diameter = {nozzle}
; filament_type = {material}
; filament_colour = {color}
; layer_height = 0.2
; first_layer_height = 0.25
; total layer number: {layers}
; printer_model = Creality K1 Max
"""
    body = "\n".join(f"G1 X{i % 100}.5 Y{i % 80}.2 E{i * 0.01:.3f} F1800" for i in range(body_lines))
    tail = f"""
; estimated printing time (normal mode) = {print_time}
; filament used [g] = 38.42
; filament used [mm] = 12874.3
; first_layer_temperature = 220
; first_layer_bed_temperature = 60
"""
    return f"{head}\nG28\nM104 S220\nM140 S60\n{body}\nM104 S0\nM140 S0\n{tail}"


def make_3mf(*, sliced: bool = False, material: str = "PETG", color: str = "#0000FF") -> bytes:
    """Projet 3MF; `sliced=True` embarque un G-code, donc imprimable."""
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(
            "[Content_Types].xml",
            '<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.'
            'org/package/2006/content-types"/>',
        )
        archive.writestr("3D/3dmodel.model", "<model/>")
        archive.writestr(
            "Metadata/project_settings.config",
            json.dumps(
                {
                    "filament_type": [material],
                    "filament_colour": [color],
                    "nozzle_diameter": ["0.4"],
                    "layer_height": "0.2",
                    "printer_settings_id": "Creality K2 Plus",
                    "from": "Creality Print",
                }
            ),
        )
        archive.writestr("Metadata/plate_1.png", TINY_PNG)
        if sliced:
            archive.writestr("Metadata/plate_1.gcode", make_gcode(material=material, color=color))
    return buffer.getvalue()


def write_samples(directory: Path) -> dict[str, Path]:
    """Ecrit un jeu d'exemples sur disque et retourne leurs chemins."""
    directory.mkdir(parents=True, exist_ok=True)
    paths = {
        "gcode": directory / "cube_pla_rouge.gcode",
        "gcode_petg": directory / "support_petg_bleu.gcode",
        "project": directory / "projet_non_tranche.3mf",
        "sliced": directory / "plateau_tranche.3mf",
    }
    paths["gcode"].write_text(make_gcode(), encoding="utf-8")
    paths["gcode_petg"].write_text(
        make_gcode(material="PETG", color="#0000FF", print_time="2h 5m"), encoding="utf-8"
    )
    paths["project"].write_bytes(make_3mf())
    paths["sliced"].write_bytes(make_3mf(sliced=True))
    return paths


if __name__ == "__main__":  # pragma: no cover
    import sys

    target = Path(sys.argv[1] if len(sys.argv) > 1 else "./samples")
    for name, path in write_samples(target).items():
        print(f"{name}: {path} ({path.stat().st_size} o)")
