"""Extraction des metadonnees de tranchage."""
from __future__ import annotations

from pathlib import Path

import pytest

from allbudy.files.gcode_meta import (
    extract_gcode_metadata,
    extract_thumbnail,
    parse_duration,
    parse_gcode_text,
)
from allbudy.files.threemf import extract_3mf_metadata
from tests.sample_data import make_3mf, make_gcode


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        ("1h 12m 30s", 4350),
        ("2d 4h", 187200),
        ("45m", 2700),
        ("30s", 30),
        ("4231", 4231),
        ("", None),
        ("bientot", None),
    ],
)
def test_parse_duration(text, expected):
    assert parse_duration(text) == expected


def test_parse_creality_gcode():
    meta = parse_gcode_text(make_gcode())
    assert meta.filament_types == ["PLA"]
    assert meta.filament_colors == ["#FF0000"]
    assert meta.layer_count == 240
    assert meta.layer_height == 0.2
    assert meta.nozzle_diameter == 0.4
    assert meta.print_time_s == 4350
    assert meta.filament_used_g == 38.42
    assert meta.slicer.startswith("CrealityPrint")


def test_parse_cura_gcode():
    """Cura utilise `;CLE:valeur` et place tout en tete."""
    text = (
        ";FLAVOR:Marlin\n"
        ";TIME:5400\n"
        ";Filament used: 4.21m\n"
        ";LAYER_COUNT:180\n"
        ";Layer height: 0.15\n"
        ";MINX:10\n"
        "G28\n"
    )
    meta = parse_gcode_text(text)
    assert meta.print_time_s == 5400
    assert meta.layer_count == 180
    assert meta.filament_used_mm == pytest.approx(4210.0)


def test_multi_material_lists():
    text = "; filament_type = PLA;PETG;ABS\n; filament_colour = #FF0000;#00FF00;#0000FF\n"
    meta = parse_gcode_text(text)
    assert meta.filament_types == ["PLA", "PETG", "ABS"]
    assert meta.filament_colors == ["#FF0000", "#00FF00", "#0000FF"]


def test_creality_print_cfs_toolchange_ne_masque_pas_les_vraies_couleurs():
    """Format reel Creality Print (CFS): un evenement de changement d'outil
    dans le corps ("; material : PLA -> PLA") et une pastille par extrudeuse
    physique ("; extruder_colour") ne doivent pas ecraser les vraies valeurs
    par materiau/couleur ecrites plus loin dans le bloc de reglages."""
    text = (
        "; CP TOOLCHANGE START\n"
        "; toolchange #1\n"
        "; material : PLA -> PLA\n"
        "; CP TOOLCHANGE END\n"
        "G28\n"
        "; extruder_colour = #FCE94F\n"
        "; filament_colour = #C12E1F;#FFFFFF\n"
        "; filament_type = PLA;PLA\n"
    )
    meta = parse_gcode_text(text)
    assert meta.filament_types == ["PLA", "PLA"]
    assert meta.filament_colors == ["#C12E1F", "#FFFFFF"]


def test_extruder_colour_sert_de_repli_si_aucune_couleur_par_materiau():
    text = "; extruder_colour = #FCE94F\n"
    meta = parse_gcode_text(text)
    assert meta.filament_colors == ["#FCE94F"]


def test_thumbnail_extraction():
    payload = extract_thumbnail(make_gcode(with_thumbnail=True))
    assert payload is not None
    assert payload.startswith(b"\x89PNG")


def test_thumbnail_absent():
    assert extract_thumbnail(make_gcode(with_thumbnail=False)) is None


def test_creality_single_line_thumbnail():
    """Creality Print encode aussi la miniature sur une ligne `;gimage:`."""
    import base64

    from tests.sample_data import TINY_PNG

    text = f";gimage:{base64.b64encode(TINY_PNG).decode()}\nG28\n"
    assert extract_thumbnail(text) == TINY_PNG


def test_metadata_in_tail(tmp_path: Path):
    """Les trancheurs derives de PrusaSlicer ecrivent le bilan en fin de fichier."""
    path = tmp_path / "gros.gcode"
    filler = "\n".join(f"G1 X{i % 200} Y{i % 200} E{i * 0.001:.4f}" for i in range(60000))
    path.write_text(
        "; generated by OrcaSlicer\nG28\n"
        + filler
        + "\n; estimated printing time (normal mode) = 3h 20m 0s\n"
        + "; filament used [g] = 120.5\n; filament_type = PETG\n",
        encoding="utf-8",
    )
    meta, _ = extract_gcode_metadata(path)
    assert meta.print_time_s == 12000
    assert meta.filament_used_g == 120.5
    assert meta.filament_types == ["PETG"]


def test_3mf_project_is_not_printable(tmp_path: Path):
    path = tmp_path / "projet.3mf"
    path.write_bytes(make_3mf(sliced=False))
    meta, thumbnail = extract_3mf_metadata(path)
    assert meta.printable is False
    assert meta.filament_types == ["PETG"]
    assert meta.filament_colors == ["#0000FF"]
    assert meta.nozzle_diameter == 0.4
    assert thumbnail is not None


def test_3mf_sliced_is_printable(tmp_path: Path):
    path = tmp_path / "tranche.3mf"
    path.write_bytes(make_3mf(sliced=True, material="ABS", color="#112233"))
    meta, _ = extract_3mf_metadata(path)
    assert meta.printable is True
    assert meta.layer_count == 240
    assert meta.filament_types == ["ABS"]


def test_3mf_corrompu(tmp_path: Path):
    path = tmp_path / "casse.3mf"
    path.write_bytes(b"ceci n'est pas une archive zip")
    with pytest.raises(ValueError):
        extract_3mf_metadata(path)


def test_analyze_ne_leve_jamais(tmp_path: Path):
    """L'import ne doit pas echouer sur un fichier illisible."""
    from allbudy.files.store import analyze

    path = tmp_path / "casse.3mf"
    path.write_bytes(b"pas un zip")
    meta, thumbnail = analyze(path, "3mf")
    assert "analysis_error" in meta
    assert thumbnail is None


# --------------------------------------------------- nombre de pieces
@pytest.mark.parametrize(
    ("text", "expected"),
    [
        # Klipper: une definition par piece, emise en tete de fichier.
        (
            "EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0\nEXCLUDE_OBJECT_DEFINE NAME=Cube_id_1\nG28\n",
            2,
        ),
        # Meme piece definie deux fois: on ne compte pas deux fois.
        ("EXCLUDE_OBJECT_DEFINE NAME=A\nEXCLUDE_OBJECT_DEFINE NAME=A\n", 1),
        # M486: l'index le plus haut donne le compte, S-1 signale "hors objet".
        ("M486 S0\nG1 X1\nM486 S1\nM486 S2\nM486 S-1\n", 3),
        # Cura nomme chaque maillage; NONMESH n'est pas une piece.
        (";MESH:a.stl\nG1\n;MESH:b.stl\n;MESH:NONMESH\n", 2),
        # Orca/PrusaSlicer annoncent l'objet en cours.
        ("; printing object Boitier\nG1\n; printing object Couvercle\n", 2),
        ("G28\nG1 X10 Y10\n", None),
    ],
)
def test_count_objects(text, expected):
    from allbudy.files.gcode_meta import count_objects

    assert count_objects(text) == expected


def test_object_count_dans_les_metadonnees():
    text = make_gcode() + "\nEXCLUDE_OBJECT_DEFINE NAME=P1\nEXCLUDE_OBJECT_DEFINE NAME=P2\n"
    assert parse_gcode_text(text).object_count == 2


def test_3mf_compte_les_pieces_du_plateau(tmp_path: Path):
    """Dans un 3MF non tranche, le compte vient des items du plateau."""
    import io
    import zipfile

    path = tmp_path / "plateau.3mf"
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr(
            "3D/3dmodel.model",
            "<model><resources><object id='1'/></resources>"
            "<build><item objectid='1'/><item objectid='1'/><item objectid='1'/></build></model>",
        )
    path.write_bytes(buffer.getvalue())
    meta, _ = extract_3mf_metadata(path)
    assert meta.object_count == 3
