"""Extraction des metadonnees de tranchage."""
from __future__ import annotations

from pathlib import Path

import pytest

from allbudy.files.gcode_meta import (
    extract_gcode_metadata,
    extract_thumbnail,
    parse_duration,
    parse_gcode_text,
)
from allbudy.files.threemf import extract_3mf_metadata
from tests.sample_data import make_3mf, make_gcode


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        ("1h 12m 30s", 4350),
        ("2d 4h", 187200),
        ("45m", 2700),
        ("30s", 30),
        ("4231", 4231),
        ("", None),
        ("bientot", None),
    ],
)
def test_parse_duration(text, expected):
    assert parse_duration(text) == expected


def test_parse_creality_gcode():
    meta = parse_gcode_text(make_gcode())
    assert meta.filament_types == ["PLA"]
    assert meta.filament_colors == ["#FF0000"]
    assert meta.layer_count == 240
    assert meta.layer_height == 0.2
    assert meta.nozzle_diameter == 0.4
    assert meta.print_time_s == 4350
    assert meta.filament_used_g == 38.42
    assert meta.slicer.startswith("CrealityPrint")


def test_parse_cura_gcode():
    """Cura utilise `;CLE:valeur` et place tout en tete."""
    text = (
        ";FLAVOR:Marlin\n"
        ";TIME:5400\n"
        ";Filament used: 4.21m\n"
        ";LAYER_COUNT:180\n"
        ";Layer height: 0.15\n"
        ";MINX:10\n"
        "G28\n"
    )
    meta = parse_gcode_text(text)
    assert meta.print_time_s == 5400
    assert meta.layer_count == 180
    assert meta.filament_used_mm == pytest.approx(4210.0)


def test_multi_material_lists():
    text = "; filament_type = PLA;PETG;ABS\n; filament_colour = #FF0000;#00FF00;#0000FF\n"
    meta = parse_gcode_text(text)
    assert meta.filament_types == ["PLA", "PETG", "ABS"]
    assert meta.filament_colors == ["#FF0000", "#00FF00", "#0000FF"]


def test_thumbnail_extraction():
    payload = extract_thumbnail(make_gcode(with_thumbnail=True))
    assert payload is not None
    assert payload.startswith(b"\x89PNG")


def test_thumbnail_absent():
    assert extract_thumbnail(make_gcode(with_thumbnail=False)) is None


def test_creality_single_line_thumbnail():
    """Creality Print encode aussi la miniature sur une ligne `;gimage:`."""
    import base64

    from tests.sample_data import TINY_PNG

    text = f";gimage:{base64.b64encode(TINY_PNG).decode()}\nG28\n"
    assert extract_thumbnail(text) == TINY_PNG


def test_metadata_in_tail(tmp_path: Path):
    """Les trancheurs derives de PrusaSlicer ecrivent le bilan en fin de fichier."""
    path = tmp_path / "gros.gcode"
    filler = "\n".join(f"G1 X{i % 200} Y{i % 200} E{i * 0.001:.4f}" for i in range(60000))
    path.write_text(
        "; generated by OrcaSlicer\nG28\n"
        + filler
        + "\n; estimated printing time (normal mode) = 3h 20m 0s\n"
        + "; filament used [g] = 120.5\n; filament_type = PETG\n",
        encoding="utf-8",
    )
    meta, _ = extract_gcode_metadata(path)
    assert meta.print_time_s == 12000
    assert meta.filament_used_g == 120.5
    assert meta.filament_types == ["PETG"]


def test_3mf_project_is_not_printable(tmp_path: Path):
    path = tmp_path / "projet.3mf"
    path.write_bytes(make_3mf(sliced=False))
    meta, thumbnail = extract_3mf_metadata(path)
    assert meta.printable is False
    assert meta.filament_types == ["PETG"]
    assert meta.filament_colors == ["#0000FF"]
    assert meta.nozzle_diameter == 0.4
    assert thumbnail is not None


def test_3mf_sliced_is_printable(tmp_path: Path):
    path = tmp_path / "tranche.3mf"
    path.write_bytes(make_3mf(sliced=True, material="ABS", color="#112233"))
    meta, _ = extract_3mf_metadata(path)
    assert meta.printable is True
    assert meta.layer_count == 240
    assert meta.filament_types == ["ABS"]


def test_3mf_corrompu(tmp_path: Path):
    path = tmp_path / "casse.3mf"
    path.write_bytes(b"ceci n'est pas une archive zip")
    with pytest.raises(ValueError):
        extract_3mf_metadata(path)


def test_analyze_ne_leve_jamais(tmp_path: Path):
    """L'import ne doit pas echouer sur un fichier illisible."""
    from allbudy.files.store import analyze

    path = tmp_path / "casse.3mf"
    path.write_bytes(b"pas un zip")
    meta, thumbnail = analyze(path, "3mf")
    assert "analysis_error" in meta
    assert thumbnail is None
